---
version: 1

name: web-community-cdn

pipelines:
  prod:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: master
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:17.09.0
        environment_variables:
          ENV: prod
          ROOT_DNS: cdn.byu.edu
          CONFIG_BRANCH: master
          CERTIFICATE_ARN: arn:aws:acm:us-east-1:427927161742:certificate/2baac981-4646-464d-a879-a1576fbc30ef
        build_role: web-community-cdn-cfn-deploy
        cache: s3
      - type: slack_notify
        name: Notify
        message: "Prod CDN Assembler Build Finished"
        channel: "@josephmoore"
  beta:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: beta
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:17.09.0
        environment_variables:
          ENV: stg
          ROOT_DNS: beta.cdn.byu.edu
          CONFIG_BRANCH: beta
          CERTIFICATE_ARN: arn:aws:acm:us-east-1:818272543125:certificate/292aa116-e65f-4121-8e40-bee4fefa5fa4
        build_role: web-community-cdn-cfn-deploy
        cache: s3
      - type: slack_notify
        name: Notify
        message: "Beta CDN Assembler Build Finished"
        channel: "@josephmoore"
  dev:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: dev
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:17.09.0
        environment_variables:
          ENV: dev
          ROOT_DNS: dev.cdn.byu.edu
          CONFIG_BRANCH: dev
          CERTIFICATE_ARN: arn:aws:acm:us-east-1:398230616010:certificate/811c7982-75e1-4565-b81b-4a4dad3e6b85
        build_role: web-community-cdn-cfn-deploy
        cache: s3
      - type: slack_notify
        name: Notify
        message: "Dev CDN Assembler Build Finished"
        channel: "@josephmoore"

